name: Build and Push ECR Image

on:
  push:
    branches:
      - main

jobs:
  ECR_ECS_Deployment:
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the tagged Docker image to Amazon ECR
        
        run: |
          docker build -t newrepositoryproject .
          docker tag newrepositoryproject:latest 529239326430.dkr.ecr.eu-west-3.amazonaws.com/newrepositoryproject:latest
          docker push 529239326430.dkr.ecr.eu-west-3.amazonaws.com/newrepositoryproject:latest