name: Build and Push ECR Image

on:
  push:
    branches:
      - main

jobs:
  ECR_ECS_Deployment:
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the tagged Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: firstcontainerformyproject
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Update Lambda function with latest ECR image
        env:
          LAMBDA_NAME: lambdatryascontainer
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: firstcontainerformyproject
        run: |
          aws lambda update-function-code \
          --function-name $LAMBDA_NAME \
          --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Invoke updated Lambda function
        env:
          LAMBDA_NAME: lambdatryascontainer
        run: |
          aws lambda invoke \
          --function-name $LAMBDA_NAME \
          --payload '{}'